# use to check sequences generated by 
# stand_alone
# usage: Rscript script file.fa depth.txt ref.fa

require(seqinr)

# read in 

args = commandArgs( trailingOnly = TRUE )

if ( length(args) !=3 ) { stop( "try - Rscript script file.fa depth.txt ref.fa
", call. = FALSE ) } 

out_fa = read.fasta( args[1], forceDNAtolower=F)
out_fa_seq = getSequence(out_fa)
out_fa_name = attributes(out_fa)$names

ref_fa = read.fasta( args[3], forceDNAtolower=F)
ref_fa_seq = getSequence(ref_fa)
ref_fa_name = attributes(ref_fa)$names

depth_txt = read.table( args[2], header=F)

# *rename sequence name 

# *fill N

low_dep = which( depth_txt$V3 < 1 )

out_fa_seq[[1]][low_dep] = "N"

# *check diff

com_seq = list( out_fa_seq[[1]], ref_fa_seq[[1]] )
max_seq = t( do.call( rbind, com_seq ) ) 

colnames(max_seq) = c( "out", "ref" )

for(i in 1:dim(max_seq)[1])
{
 if( max_seq[i,1] != max_seq[i,2] )
  {
    cat( paste0( "pos.",i, "\n" ) )
    print( max_seq[i,] )
  }
}



# * output

#write.fasta( sequences=out_fa_seq, names=args[1], 
 #            file.out="new_seq.fa" ) 
